version: '3'
services:
  trpc:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: parker_user
      POSTGRES_PASSWORD: paker_password
      POSTGRES_DB: parker_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  node_modules:
  next:
