version: '3'
services:
  trpc:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: parker_db
      POSTGRES_HOST: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data:
  node_modules:
  next:
